import{S as d}from"./assets/vendor-874053e3.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const u=document.querySelector("form"),a=document.querySelector("input"),c=document.querySelector(".gallery"),i=document.querySelector(".loader");i.style.display="none";u.addEventListener("submit",function(l){l.preventDefault();const s=a.value.trim();s&&(i.style.display="block",fetch(`https://pixabay.com/api/?key=42259333-3fd7a9af9caf7b06e8f99497c&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()}).then(o=>{i.style.display="none",o.hits.length>0?(c.innerHTML="",o.hits.forEach(r=>{const e=document.createElement("img");e.src=r.webformatURL,e.alt=r.tags,e.title=r.tags;const t=document.createElement("div");t.classList.add("caption"),t.innerHTML=`
                                <ul class="caption-list">
                                    <li class="caption-text">Views: ${r.views}</li>
                                    <li class="caption-text">Likes: ${r.likes}</li>
                                    <li class="caption-text">Comments: ${r.comments}</li>
                                    <li class="caption-text">Downloads: ${r.downloads}</li>
                                </ul>
                            `;const n=document.createElement("a");n.href=r.largeImageURL,n.classList.add("image-card"),n.appendChild(e),n.appendChild(t),c.appendChild(n)}),new d(".gallery a",{})):c.innerHTML="Sorry, there are no images matching your search query. Please try again!",a.value=""}).catch(o=>{console.error("Error fetching data:",o),i.style.display="none"}))});
//# sourceMappingURL=commonHelpers.js.map
